{
  // The container_name of this container is `vendor/confetti-cms/image/container`.
  description: "This package allows you to upload and edit images in the dashboard.",
  "sync_granted": [
    {
      description: "Other containers in this (umbrella) organization should have read access to the stored images.",
      scheme: "images",
      expose_path: "/var/storage",
      readonly: true,
      source_organization: "*",
      source_repository: "*",
      container_name: "*",
      target: "*",
    },
  ],
}
